spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5555/student_management
    username: postgres
    password: password

server:
  port: 9000

jpa:
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      use_sql_comments: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.validator: DEBUG
    org.springframework.validation: DEBUG
    org.example.backend.validator: DEBUG


cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true