spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5555/student_management
    username: postgres
    password: password

server:
  port: 9000

jpa:
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      use_sql_comments: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.validator: DEBUG
    org.springframework.validation: DEBUG
    org.example.backend.validator: DEBUG


cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
    allowed-headers: "*"
    allow-credentials: false

# SpringDoc specific settings
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf.enabled: false
    disable-swagger-default-url: true
    operationsSorter: method