version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_management
    ports:
        - '5555:5432'
    volumes:
        - pg_data:/var/lib/postgresql/data
    networks:
        - student_management-network
volumes:
    pg_data:
networks:
  student_management-network:
