spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5555/student_management_system
    username: postgres
    password: password


jpa:
    hibernate:
        ddl-auto: validate
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true
            use_sql_comments: true
